name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: check out code
      uses: actions/checkout@v4
    - name: set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.26'
    - name: install golint
      run: go install golang.org/x/lint/golint@latest
    - name: run tests
      run: make test
